/**
 *
 * Copyright 2013 Martin Goellnitz
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
 * Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 *
 */
package org.tangram.ebean;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.tangram.content.Content;
import org.tangram.mutable.MutableContent;


/**
 * Content base class for EBean.
 *
 * Sad enough ebean only seems to support single table inhertance strategy.
 */
@Entity
public abstract class EContent implements MutableContent {

    private static final Log log = LogFactory.getLog(EContent.class);

    @Id
    @GeneratedValue
    private Integer internalId;


    public Integer getInternalId() {
        return internalId;
    }


    /**
     * returns the string representation of the objects persistent ID.
     *
     * Be aware not to call this before the object has been persisted!
     */
    @Override
    public String getId() {
        String kind = getClass().getSimpleName();
        if (kind.indexOf('$') >= 0) {
            kind = getClass().getSuperclass().getSimpleName();
        } // if
        return kind+":"+internalId;
    } // getId()


    /* gets generated by Ebean's enhancer
    @Override
    public int hashCode() {
        return internalId==null ? 0 : internalId.hashCode();
    } // hashCode()


    @Override
    public boolean equals(Object obj) {
        return (obj instanceof EContent) ? getId().equals(((Content) obj).getId()) : super.equals(obj);
    } // equals()
    */


    @Override
    public int compareTo(Content c) {
        return getId().compareTo(c.getId());
    } // compareTo()


    @Override
    public String toString() {
        return getClass().getSimpleName()+"/"+getId();
    } // toString()

} // EContent
